// AUTO-GENERATED by scripts/discoverGoodreturnsCoverage.ts
// Do not edit manually.

export const CITY_SLUGS: Record<string, { city: string; slug: string }[]> = {
  "DL": [
    {
      "city": "Central Delhi",
      "slug": "central-delhi"
    },
    {
      "city": "Delhi Shahdara",
      "slug": "delhi-shahdara"
    },
    {
      "city": "East Delhi",
      "slug": "east-delhi"
    },
    {
      "city": "New Delhi",
      "slug": "new-delhi"
    },
    {
      "city": "North Delhi",
      "slug": "north-delhi"
    },
    {
      "city": "North East Delhi",
      "slug": "north-east-delhi"
    },
    {
      "city": "North West Delhi",
      "slug": "north-west-delhi"
    },
    {
      "city": "South Delhi",
      "slug": "south-delhi"
    },
    {
      "city": "South East Delhi",
      "slug": "south-east-delhi"
    },
    {
      "city": "South West Delhi",
      "slug": "south-west-delhi"
    },
    {
      "city": "West Delhi",
      "slug": "west-delhi"
    }
  ],
  "GJ": [
    {
      "city": "Ahmedabad",
      "slug": "ahmedabad"
    },
    {
      "city": "Amreli",
      "slug": "amreli"
    },
    {
      "city": "Anand",
      "slug": "anand"
    },
    {
      "city": "Aravalli",
      "slug": "aravalli"
    },
    {
      "city": "Banas Kantha",
      "slug": "banas-kantha"
    },
    {
      "city": "Bharuch",
      "slug": "bharuch"
    },
    {
      "city": "Bhavnagar",
      "slug": "bhavnagar"
    },
    {
      "city": "Botad",
      "slug": "botad"
    },
    {
      "city": "Chhotaudepur",
      "slug": "chhotaudepur"
    },
    {
      "city": "Dahod",
      "slug": "dahod"
    },
    {
      "city": "Devbhumi Dwarka",
      "slug": "devbhumi-dwarka"
    },
    {
      "city": "Gandhinagar",
      "slug": "gandhinagar"
    },
    {
      "city": "Gir Somnath",
      "slug": "gir-somnath"
    },
    {
      "city": "Jamnagar",
      "slug": "jamnagar"
    },
    {
      "city": "Junagadh",
      "slug": "junagadh"
    },
    {
      "city": "Kheda",
      "slug": "kheda"
    },
    {
      "city": "Kutch",
      "slug": "kutch"
    },
    {
      "city": "Mahisagar",
      "slug": "mahisagar"
    },
    {
      "city": "Mehsana",
      "slug": "mehsana"
    },
    {
      "city": "Morbi",
      "slug": "morbi"
    },
    {
      "city": "Narmada",
      "slug": "narmada"
    },
    {
      "city": "Navsari",
      "slug": "navsari"
    },
    {
      "city": "Panch Mahal",
      "slug": "panch-mahal"
    },
    {
      "city": "Patan",
      "slug": "patan"
    },
    {
      "city": "Porbander",
      "slug": "porbander"
    },
    {
      "city": "Rajkot",
      "slug": "rajkot"
    },
    {
      "city": "Sabar Kantha",
      "slug": "sabar-kantha"
    },
    {
      "city": "Surat",
      "slug": "surat"
    },
    {
      "city": "Surendranagar",
      "slug": "surendranagar"
    },
    {
      "city": "Tapi",
      "slug": "tapi"
    },
    {
      "city": "The Dangs",
      "slug": "the-dangs"
    },
    {
      "city": "Vadodara",
      "slug": "vadodara"
    },
    {
      "city": "Valsad",
      "slug": "valsad"
    }
  ],
  "KA": [
    {
      "city": "Bagalkot",
      "slug": "bagalkot"
    },
    {
      "city": "Bangalore",
      "slug": "bangalore"
    },
    {
      "city": "Bangalore Rural",
      "slug": "bangalore-rural"
    },
    {
      "city": "Belgaum",
      "slug": "belgaum"
    },
    {
      "city": "Bellary",
      "slug": "bellary"
    },
    {
      "city": "Bidar",
      "slug": "bidar"
    },
    {
      "city": "Bijapur",
      "slug": "bijapur"
    },
    {
      "city": "Chamrajnagar",
      "slug": "chamrajnagar"
    },
    {
      "city": "Chikkaballapura",
      "slug": "chikkaballapura"
    },
    {
      "city": "Chikmagalur",
      "slug": "chikmagalur"
    },
    {
      "city": "Chitradurga",
      "slug": "chitradurga"
    },
    {
      "city": "Dakshina Kannada",
      "slug": "dakshina-kannada"
    },
    {
      "city": "Davangere",
      "slug": "davangere"
    },
    {
      "city": "Dharwad",
      "slug": "dharwad"
    },
    {
      "city": "Gadag",
      "slug": "gadag"
    },
    {
      "city": "Gulbarga",
      "slug": "gulbarga"
    },
    {
      "city": "Hassan",
      "slug": "hassan"
    },
    {
      "city": "Haveri",
      "slug": "haveri"
    },
    {
      "city": "Kodagu",
      "slug": "kodagu"
    },
    {
      "city": "Kolar",
      "slug": "kolar"
    },
    {
      "city": "Koppal",
      "slug": "koppal"
    },
    {
      "city": "Mandya",
      "slug": "mandya"
    },
    {
      "city": "Mysore",
      "slug": "mysore"
    },
    {
      "city": "Raichur",
      "slug": "raichur"
    },
    {
      "city": "Ramanagara",
      "slug": "ramanagara"
    },
    {
      "city": "Shimoga",
      "slug": "shimoga"
    },
    {
      "city": "Tumkur",
      "slug": "tumkur"
    },
    {
      "city": "Udupi",
      "slug": "udupi"
    },
    {
      "city": "Uttara Kannada",
      "slug": "uttara-kannada"
    },
    {
      "city": "Vijayanagara",
      "slug": "vijayanagara"
    },
    {
      "city": "Yadgir",
      "slug": "yadgir"
    }
  ],
  "KL": [
    {
      "city": "Alappuzha",
      "slug": "alappuzha"
    },
    {
      "city": "Ernakulam",
      "slug": "ernakulam"
    },
    {
      "city": "Idukki",
      "slug": "idukki"
    },
    {
      "city": "Kannur",
      "slug": "kannur"
    },
    {
      "city": "Kasaragod",
      "slug": "kasaragod"
    },
    {
      "city": "Kollam",
      "slug": "kollam"
    },
    {
      "city": "Kottayam",
      "slug": "kottayam"
    },
    {
      "city": "Kozhikode",
      "slug": "kozhikode"
    },
    {
      "city": "Malappuram",
      "slug": "malappuram"
    },
    {
      "city": "Palakkad",
      "slug": "palakkad"
    },
    {
      "city": "Pathananthitta",
      "slug": "pathananthitta"
    },
    {
      "city": "Thiruvananthapuram",
      "slug": "trivandrum"
    },
    {
      "city": "Thrissur",
      "slug": "thrissur"
    },
    {
      "city": "Wayanad",
      "slug": "wayanad"
    }
  ],
  "MH": [
    {
      "city": "Ahmadnagar",
      "slug": "ahmadnagar"
    },
    {
      "city": "Akola",
      "slug": "akola"
    },
    {
      "city": "Amravati",
      "slug": "amravati"
    },
    {
      "city": "Aurangabad",
      "slug": "aurangabad"
    },
    {
      "city": "Bhandara",
      "slug": "bhandara"
    },
    {
      "city": "Bid",
      "slug": "bid"
    },
    {
      "city": "Buldhana",
      "slug": "buldhana"
    },
    {
      "city": "Chandrapur",
      "slug": "chandrapur"
    },
    {
      "city": "Dhule",
      "slug": "dhule"
    },
    {
      "city": "Gadchiroli",
      "slug": "gadchiroli"
    },
    {
      "city": "Gondia",
      "slug": "gondia"
    },
    {
      "city": "Greater Mumbai",
      "slug": "greater-mumbai"
    },
    {
      "city": "Hingoli",
      "slug": "hingoli"
    },
    {
      "city": "Jalgaon",
      "slug": "jalgaon"
    },
    {
      "city": "Jalna",
      "slug": "jalna"
    },
    {
      "city": "Kolhapur",
      "slug": "kolhapur"
    },
    {
      "city": "Latur",
      "slug": "latur"
    },
    {
      "city": "Mumbai",
      "slug": "mumbai"
    },
    {
      "city": "Nagpur",
      "slug": "nagpur"
    },
    {
      "city": "Nanded",
      "slug": "nanded"
    },
    {
      "city": "Nandurbar",
      "slug": "nandurbar"
    },
    {
      "city": "Nashik",
      "slug": "nashik"
    },
    {
      "city": "Osmanabad",
      "slug": "osmanabad"
    },
    {
      "city": "Palghar",
      "slug": "palghar"
    },
    {
      "city": "Parbhani",
      "slug": "parbhani"
    },
    {
      "city": "Pune",
      "slug": "pune"
    },
    {
      "city": "Raigarh",
      "slug": "raigarh"
    },
    {
      "city": "Ratnagiri",
      "slug": "ratnagiri"
    },
    {
      "city": "Sangli",
      "slug": "sangli"
    },
    {
      "city": "Satara",
      "slug": "satara"
    },
    {
      "city": "Sindhudurg",
      "slug": "sindhudurg"
    },
    {
      "city": "Solapur",
      "slug": "solapur"
    },
    {
      "city": "Thane",
      "slug": "thane"
    },
    {
      "city": "Wardha",
      "slug": "wardha"
    },
    {
      "city": "Washim",
      "slug": "washim"
    },
    {
      "city": "Yavatmal",
      "slug": "yavatmal"
    }
  ],
  "TN": [
    {
      "city": "Ariyalur",
      "slug": "ariyalur"
    },
    {
      "city": "Chengalpattu",
      "slug": "chengalpattu"
    },
    {
      "city": "Chennai",
      "slug": "chennai"
    },
    {
      "city": "Coimbatore",
      "slug": "coimbatore"
    },
    {
      "city": "Cuddalore",
      "slug": "cuddalore"
    },
    {
      "city": "Dharmapuri",
      "slug": "dharmapuri"
    },
    {
      "city": "Dindigul",
      "slug": "dindigul"
    },
    {
      "city": "Erode",
      "slug": "erode"
    },
    {
      "city": "Kallakurichi",
      "slug": "kallakurichi"
    },
    {
      "city": "Kanchipuram",
      "slug": "kanchipuram"
    },
    {
      "city": "Kanniyakumari",
      "slug": "kanniyakumari"
    },
    {
      "city": "Karur",
      "slug": "karur"
    },
    {
      "city": "Krishnagiri",
      "slug": "krishnagiri"
    },
    {
      "city": "Madurai",
      "slug": "madurai"
    },
    {
      "city": "Mayiladuthurai",
      "slug": "mayiladuthurai"
    },
    {
      "city": "Nagapattinam",
      "slug": "nagapattinam"
    },
    {
      "city": "Namakkal",
      "slug": "namakkal"
    },
    {
      "city": "Nilgiris",
      "slug": "nilgiris"
    },
    {
      "city": "Perambalur",
      "slug": "perambalur"
    },
    {
      "city": "Pudukkottai",
      "slug": "pudukkottai"
    },
    {
      "city": "Ramanathapuram",
      "slug": "ramanathapuram"
    },
    {
      "city": "Ranipet",
      "slug": "ranipet"
    },
    {
      "city": "Salem",
      "slug": "salem"
    },
    {
      "city": "Sivaganga",
      "slug": "sivaganga"
    },
    {
      "city": "Teni",
      "slug": "teni"
    },
    {
      "city": "Tenkasi",
      "slug": "tenkasi"
    },
    {
      "city": "Thanjavur",
      "slug": "thanjavur"
    },
    {
      "city": "Thiruvarur",
      "slug": "thiruvarur"
    },
    {
      "city": "Tiruchchirappalli",
      "slug": "tiruchchirappalli"
    },
    {
      "city": "Tirunelveli",
      "slug": "tirunelveli"
    },
    {
      "city": "Tirupathur",
      "slug": "tirupathur"
    },
    {
      "city": "Tirupur",
      "slug": "tirupur"
    },
    {
      "city": "Tiruvallur",
      "slug": "tiruvallur"
    },
    {
      "city": "Tiruvannamalai",
      "slug": "tiruvannamalai"
    },
    {
      "city": "Tuticorin",
      "slug": "tuticorin"
    },
    {
      "city": "Vellore",
      "slug": "vellore"
    },
    {
      "city": "Viluppuram",
      "slug": "viluppuram"
    },
    {
      "city": "Virudunagar",
      "slug": "virudunagar"
    }
  ],
  "UP": [
    {
      "city": "Agra",
      "slug": "agra"
    },
    {
      "city": "Aligarh",
      "slug": "aligarh"
    },
    {
      "city": "Ambedkarnagar",
      "slug": "ambedkarnagar"
    },
    {
      "city": "Amethi/csm Nagar",
      "slug": "amethi-csm-nagar"
    },
    {
      "city": "Amroha",
      "slug": "amroha"
    },
    {
      "city": "Auraiya",
      "slug": "auraiya"
    },
    {
      "city": "Azamgarh",
      "slug": "azamgarh"
    },
    {
      "city": "Baghpat",
      "slug": "baghpat"
    },
    {
      "city": "Bahraich",
      "slug": "bahraich"
    },
    {
      "city": "Ballia",
      "slug": "ballia"
    },
    {
      "city": "Balrampur",
      "slug": "balrampur"
    },
    {
      "city": "Banda",
      "slug": "banda"
    },
    {
      "city": "Barabanki",
      "slug": "barabanki"
    },
    {
      "city": "Bareilly",
      "slug": "bareilly"
    },
    {
      "city": "Basti",
      "slug": "basti"
    },
    {
      "city": "Bhadohi",
      "slug": "bhadohi"
    },
    {
      "city": "Bijnor",
      "slug": "bijnor"
    },
    {
      "city": "Budaun",
      "slug": "budaun"
    },
    {
      "city": "Bulandshahr",
      "slug": "bulandshahr"
    },
    {
      "city": "Chandauli",
      "slug": "chandauli"
    },
    {
      "city": "Chitrakut",
      "slug": "chitrakut"
    },
    {
      "city": "Deoria",
      "slug": "deoria"
    },
    {
      "city": "Etah",
      "slug": "etah"
    },
    {
      "city": "Etawah",
      "slug": "etawah"
    },
    {
      "city": "Faizabad",
      "slug": "faizabad"
    },
    {
      "city": "Farrukkhabad",
      "slug": "farrukkhabad"
    },
    {
      "city": "Fatehpur",
      "slug": "fatehpur"
    },
    {
      "city": "Firozabad",
      "slug": "firozabad"
    },
    {
      "city": "Gautam Budh Nagar",
      "slug": "gautam-budh-nagar"
    },
    {
      "city": "Ghaziabad",
      "slug": "ghaziabad"
    },
    {
      "city": "Ghazipur",
      "slug": "ghazipur"
    },
    {
      "city": "Gonda",
      "slug": "gonda"
    },
    {
      "city": "Gorakhpur",
      "slug": "gorakhpur"
    },
    {
      "city": "Hamirpur",
      "slug": "hamirpur"
    },
    {
      "city": "Hapur",
      "slug": "hapur"
    },
    {
      "city": "Hardoi",
      "slug": "hardoi"
    },
    {
      "city": "Hathras",
      "slug": "hathras"
    },
    {
      "city": "Jalaun",
      "slug": "jalaun"
    },
    {
      "city": "Jaunpur",
      "slug": "jaunpur"
    },
    {
      "city": "Jhansi",
      "slug": "jhansi"
    },
    {
      "city": "Kannuaj",
      "slug": "kannuaj"
    },
    {
      "city": "Kanpur Rural",
      "slug": "kanpur-rural"
    },
    {
      "city": "Kanpur Urban",
      "slug": "kanpur-urban"
    },
    {
      "city": "Kashi Ram Nagar",
      "slug": "kashi-ram-nagar"
    },
    {
      "city": "Kaushambi",
      "slug": "kaushambi"
    },
    {
      "city": "Kushinagar",
      "slug": "kushinagar"
    },
    {
      "city": "Lakhimpur",
      "slug": "lakhimpur"
    },
    {
      "city": "Lalitpur",
      "slug": "lalitpur"
    },
    {
      "city": "Lucknow",
      "slug": "lucknow"
    },
    {
      "city": "Maharajganj",
      "slug": "maharajganj"
    },
    {
      "city": "Mahoba",
      "slug": "mahoba"
    },
    {
      "city": "Mainpuri",
      "slug": "mainpuri"
    },
    {
      "city": "Mathura",
      "slug": "mathura"
    },
    {
      "city": "Maunathbhanjan",
      "slug": "maunathbhanjan"
    },
    {
      "city": "Meerut",
      "slug": "meerut"
    },
    {
      "city": "Mirzapur",
      "slug": "mirzapur"
    },
    {
      "city": "Moradabad",
      "slug": "moradabad"
    },
    {
      "city": "Muzaffarnagar",
      "slug": "muzaffarnagar"
    },
    {
      "city": "Noida",
      "slug": "noida"
    },
    {
      "city": "Pilibhit",
      "slug": "pilibhit"
    },
    {
      "city": "Pratapgarh",
      "slug": "pratapgarh"
    },
    {
      "city": "Prayagraj",
      "slug": "prayagraj"
    },
    {
      "city": "Rae Bareli",
      "slug": "rae-bareli"
    },
    {
      "city": "Rampur",
      "slug": "rampur"
    },
    {
      "city": "Saharanpur",
      "slug": "saharanpur"
    },
    {
      "city": "Sambhal",
      "slug": "sambhal"
    },
    {
      "city": "Sant Kabir Nagar",
      "slug": "sant-kabir-nagar"
    },
    {
      "city": "Shahjahanpur",
      "slug": "shahjahanpur"
    },
    {
      "city": "Shamli",
      "slug": "shamli"
    },
    {
      "city": "Shravasti",
      "slug": "shravasti"
    },
    {
      "city": "Sidharthnagar",
      "slug": "sidharthnagar"
    },
    {
      "city": "Sitapur",
      "slug": "sitapur"
    },
    {
      "city": "Sonbhadra",
      "slug": "sonbhadra"
    },
    {
      "city": "Sultanpur",
      "slug": "sultanpur"
    },
    {
      "city": "Unnao",
      "slug": "unnao"
    },
    {
      "city": "Varanasi",
      "slug": "varanasi"
    }
  ],
  "WB": [
    {
      "city": "Alipurduar",
      "slug": "alipurduar"
    },
    {
      "city": "Bankura",
      "slug": "bankura"
    },
    {
      "city": "Birbhum",
      "slug": "birbhum"
    },
    {
      "city": "Cooch Bihar",
      "slug": "cooch-bihar"
    },
    {
      "city": "Dakshin Dinajpur",
      "slug": "dakshin-dinajpur"
    },
    {
      "city": "Darjeeling",
      "slug": "darjeeling"
    },
    {
      "city": "Hooghly",
      "slug": "hooghly"
    },
    {
      "city": "Howrah",
      "slug": "howrah"
    },
    {
      "city": "Jalpaiguri",
      "slug": "jalpaiguri"
    },
    {
      "city": "Jhargram",
      "slug": "jhargram"
    },
    {
      "city": "Kalimpong",
      "slug": "kalimpong"
    },
    {
      "city": "Kolkata",
      "slug": "kolkata"
    },
    {
      "city": "Malda",
      "slug": "malda"
    },
    {
      "city": "Murshidabad",
      "slug": "murshidabad"
    },
    {
      "city": "Nadia",
      "slug": "nadia"
    },
    {
      "city": "North 24 Parganas",
      "slug": "north-24-parganas"
    },
    {
      "city": "Paschim Bardhaman",
      "slug": "paschim-bardhaman"
    },
    {
      "city": "Paschim Medinipur",
      "slug": "paschim-medinipur"
    },
    {
      "city": "Purba Bardhaman",
      "slug": "purba-bardhaman"
    },
    {
      "city": "Purba Medinipur",
      "slug": "purba-medinipur"
    },
    {
      "city": "Purulia",
      "slug": "purulia"
    },
    {
      "city": "South 24 Parganas",
      "slug": "south-24-parganas"
    },
    {
      "city": "Uttar Dinajpur",
      "slug": "uttar-dinajpur"
    }
  ]
} as Record<string, { city: string; slug: string }[]>;
