export const STATE_CITIES: Record<string, string[]> = {
    KL: [
        "Ernakulam",
        "Alappuzha",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Malappuram",
        "Palakkad",
        "Pathananthitta",
        "Thiruvananthapuram",
        "Thrissur",
        "Wayanad",
    ],
    MH: [
        "Mumbai",
        "Pune",
        "Nagpur",
        "Nashik",
        "Thane",
        "Aurangabad",
        "Solapur",
        "Kolhapur",
        "Navi Mumbai",
        "Amravati",
    ],
    KA: [
        "Bengaluru",
        "Mysuru",
        "Mangaluru",
        "Hubballi",
        "Belagavi",
        "Tumakuru",
        "Shivamogga",
        "Ballari",
        "Davangere",
        "Udupi",
    ],
    TN: [
        "Chennai",
        "Coimbatore",
        "Madurai",
        "Tiruchirappalli",
        "Salem",
        "Tirunelveli",
        "Erode",
        "Vellore",
        "Tiruppur",
        "Nagercoil",
    ],
    GJ: [
        "Ahmedabad",
        "Surat",
        "Vadodara",
        "Rajkot",
        "Bhavnagar",
        "Jamnagar",
        "Junagadh",
        "Gandhinagar",
        "Anand",
        "Navsari",
    ],
    DL: ["New Delhi", "Delhi"],
    UP: [
        "Lucknow",
        "Kanpur",
        "Varanasi",
        "Agra",
        "Noida",
        "Ghaziabad",
        "Meerut",
        "Prayagraj",
        "Bareilly",
        "Aligarh",
    ],
    WB: [
        "Kolkata",
        "Howrah",
        "Durgapur",
        "Asansol",
        "Siliguri",
        "Bardhaman",
        "Malda",
        "Kharagpur",
        "Krishnanagar",
        "Haldia",
    ],
};

export const STATE_NAMES: Record<string, string> = {
    KL: "Kerala",
    MH: "Maharashtra",
    KA: "Karnataka",
    TN: "Tamil Nadu",
    GJ: "Gujarat",
    DL: "Delhi",
    UP: "Uttar Pradesh",
    WB: "West Bengal",
};

export function getStateName(code: string): string {
    return STATE_NAMES[code] ?? code;
}
